### ISSUE TITLE
Build/publish fails when projects are still loading

### ISSUE THREAD

**Issue by LwServices** [nforgeio/RaspberryDebugger#21]
After update to 0.6 try to verify changes. Now its look like this Extension don't work at all.

![image](https://user-images.githubusercontent.com/667742/102890143-3f9f0c00-445c-11eb-965e-7fd9efbee7da.png)

I already tried to 
-different Project (what worked yesterday)
-clean solution
-restart visual studio / pc

How I can enable the log for RaspberryDebugger? Where is the log located?

**Comment by jefflill** [comment]
The debugger just writes to Visual Studio's **Output (Debug)** pane:

![image](https://user-images.githubusercontent.com/4908431/103325043-c4f76300-49fe-11eb-916e-0b5d5c3292d3.png)

Please let me know what you find.  The extension should write the stdout/stderr output from the `dotnet publish` operation to the output pane when the tool returns a non-zero exit code.

I did just notice that projects in solution folders still aren't working and I'll have a look at that.

**Comment by jefflill** [comment]
I'm poking around on this and am seeing some odd behavior.  On my machine this this mostly works but occasionally doesn't.  I'm going to investigate further,

**Comment by jefflill** [comment]
I might be narrowing this down a bit.  This seems to be a problem while Visual Studio is **executing background tasks** just after being launched.  I'm seeing three different behaviors:

1. If you click the **Start** debugging button as soon as it appears after launching Visual Studio, we generally see the project being launched locally on the development workstation (not on the Raspberry).  The root cause here is that Visual Studio is loading extensions asynchronously and the Raspberry Debugger extension hasn't been loaded yet so it can't intercept the run command.

2. If I wait a bit after launching Visual Studio and opening the solution and start debugging after our extension has been loaded but before Visual Studio reports that the projects are loaded and ready, I see **System.AccessViolationException** exceptions.

3. If I wait for Visual Studio to complete all of its background tasks after launching, Raspberry debugging seems to work every time.

**Comment by jefflill** [comment]
It looks like this is fixed.  I was able to reproduce this consistently by:

1. Launch the extension in the debugger
2. Wait for VS to display it's **Getting Started** dialog
3. Wait 20 seconds to give VS a chance to load our extension
4. Open the test solution and then press F5 as soon you can to initiate the build/publish/debug

I'd see various bad things happen here, including:

* Memory access exceptions
* VS crashes and restarts
* Publish fails

I resolved this by ensuring that the projects are fully loaded within our `DebugStartCommand` via the `SVsSolution.EnsureProjectIsLoaded()` service method.  After this change, I'm unable to reproduce the problem by following the steps above.

**Comment by jefflill** [comment]
FIXED for v1.1
