### ISSUE TITLE
Publish Failed on second build

### ISSUE THREAD

**Issue by tomasztynor** [nforgeio/RaspberryDebugger#28]
Hello,
I get an error on the second build. I have to reset VS and it works fine.
![image](https://user-images.githubusercontent.com/60470209/110750221-6fcb9f00-8242-11eb-8bbc-a424f0189b19.png)

I have such logs in the output:
[raspberry]: INFO: Checking for native Windows OpenSSH client
[raspberry]: INFO: Building: test.csproj
[raspberry]: ERROR: Build failed: [1] errors
Otherwise good work. very useful extension 👍

**Comment by jefflill** [comment]
Hmmm.  I'll have to add some code to capture the build/publish output when it fails.

**Comment by jefflill** [comment]
...and thanks for the thumbs-up.  This was my first VS extension and it's been fun.

**Comment by jefflill** [comment]
I have a feeling this is happening because we're executing `dotnet publish...` within the context of the Visual Studio process.  I've seen problems like this in the past where these two were fighting each other over file access.  I think that Visual Studio's configures some environment variables to coordinate with `dotnet` processes managed by VS and that these are messing with the `dotnet publish...` process the debugger kicks off,

I've fixed this in the past for another project by removing most environment variables before invoking `dotnet`.  Let's see if I can do that here.

**Comment by jefflill** [comment]
**FIXED** for v1.4 (hopefully)

@tomasztynor: I've just published v1.4 that hopefully fixed this problem (I wasn't actually able to repro it).  It can take some time for extension updates to become available in Visual Studio.  You can download the extension directly from the release if necessary:

https://github.com/nforgeio/RaspberryDebugger/releases/tag/v1.4

**Comment by jefflill** [comment]
...please reopen this if you have any more problems.
